name: Publish Docker Image

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}
          #password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
            #, linux/arm/V8
          push: true
          tags: ghcr.io/sachapan/getsubs:latest
          #${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}
          #tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
          #tags: ghcr.io/sachapan/getsubs:${{ github.sha }}
